/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FetchType = IDL.Variant({ 'rss' : IDL.Null, 'json' : IDL.Null });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const JobSource = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'fetchType' : FetchType,
  'name' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const Filter = IDL.Record({
  'keywords' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const JobListing = IDL.Record({
  'title' : IDL.Text,
  'applyUrl' : IDL.Text,
  'source' : IDL.Text,
  'date' : IDL.Text,
  'company' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJobSource' : IDL.Func([IDL.Text, IDL.Text, FetchType], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteJobSource' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEnabledJobSources' : IDL.Func([], [IDL.Vec(JobSource)], ['query']),
  'getJobSources' : IDL.Func([], [IDL.Vec(JobSource)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchJobs' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(Filter)],
      [IDL.Vec(JobListing)],
      ['query'],
    ),
  'toggleJobSource' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateJobSource' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, FetchType],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FetchType = IDL.Variant({ 'rss' : IDL.Null, 'json' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const JobSource = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'fetchType' : FetchType,
    'name' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const Filter = IDL.Record({
    'keywords' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const JobListing = IDL.Record({
    'title' : IDL.Text,
    'applyUrl' : IDL.Text,
    'source' : IDL.Text,
    'date' : IDL.Text,
    'company' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJobSource' : IDL.Func([IDL.Text, IDL.Text, FetchType], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteJobSource' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEnabledJobSources' : IDL.Func([], [IDL.Vec(JobSource)], ['query']),
    'getJobSources' : IDL.Func([], [IDL.Vec(JobSource)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchJobs' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(Filter)],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'toggleJobSource' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateJobSource' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, FetchType],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };